language: ruby
cache: bundler
before_install: "gem install bundler"
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
gemfile:
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_latest.gemfile
script: "bundle exec rake test"